### ISSUE TITLE
Feature request - output file

### ISSUE THREAD

**Issue by Lexus89** [sensepost/hostapd-mana#12] opened 2017-02-03 19:13 UTC
I can't seem to find a log file option in the configs to store received EAP creds (challenge/response hashes, gtc plain text passwords etc.) It would be nice to have a simple log file containing the creds so you don't need to scroll through your terminal output.

**Comment by singe** [comment] 2017-02-05 19:30
I'm sorry I didn't document that. Challenge response (or in a rare case plain text creds) are logged to a file specified in the ennode option. mana-toolkit makes it a fifo but you can make it a file http://github.com/sensepost/mana/blob/master/run-mana/conf/hostapd-mana-eaponly.conf#L58

I'll clean that up and document it. I've also been meaning to log more details.

**Comment by Lexus89** [comment] 2017-02-05 21:20
Thanks for the reply, would be nice if fifo and log file can be used at the same time.

Btw, i was wondering about the eap dumb-down implementation of hostapd-mana (if it has). Does it by default set the preferred eap type to GTC-PAP? For example mobile phone set the outer type to Peap but often not explicitly state mschapv2 as inner methode. Since mobile devices often support GTC (plain text) this can be 'enforced' server side for inner authenticition. Is this technique also used op just by default trying to get PAP (which needs the device to have been configured with a PAP eap type)?

**Comment by dhd0004** [comment] 2017-10-06 07:43
Hi,
Did you find how to make  EAP dumb-down attack works in hostapd-mana? Y see that the android device just try to use MSCHAPv2 instead of GTC, even when it does not have 2phase authentication method selected.
WIth freeradius-wpe I can make this attack works, but not with hostpad-mana.

Regards

**Comment by singe** [comment] 2018-05-21 10:54
Documented the ennode https://github.com/sensepost/hostapd-mana/commit/a3c668bcf91625bd20d9994c44f92ecedd53643e Not sure why I didn't do this sooner.

Thanks for the GTC. It's a duplicate of #13 so I'll close this one.

**Closed by singe** 2018-05-21 10:54 UTC
Labels: duplicate
